package(default_visibility = ["//visibility:public"])

cc_library(
    name = "graph",
    hdrs = [
      "Graph.h",
    ],
    srcs = [
        "Graph.cpp",
    ],
    deps = [
        "@llvm-project//mlir:IR",
    ],
)
